name: ea-python-github
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  # Core scientific python
  - matplotlib
  - pandas

  # Spatial packages
  - earthpy>=0.9.2

  # Jupyter Environment
  - papermill

  # PEP 8
  - flake8_nb
